In [1]:
import pandas as pd

train = pd.read_csv("../data/train.csv")
test = pd.read_csv("../data/test.csv")

print("Train shape:", train.shape)
print("Test shape:", test.shape)

train.head()

Train shape: (17769, 4)
Test shape: (4797, 3)

,id,feedback,tag,label
0,0,bugun 2 velosipod goturdum ikisinin de tormozu...,NaN,technical_support
1,1,sol pedalda problem var bu veloda,NaN,technical_support
2,2,Oturacağın alt-ön tərəfi çıxıb dəyişilməlidir,Other,technical_support
3,3,velospied kilidə düşmürdü,NaN,technical_support
4,4,Gprs islemir anbara getmelidi,Electrical system,technical_support

In [2]:
train.shape

(17769, 4)

In [3]:
train.columns

Index(['id', 'feedback', 'tag', 'label'], dtype='str')

In [4]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 17769 entries, 0 to 17768
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        17769 non-null  int64
 1   feedback  17769 non-null  str
 2   tag       5265 non-null   str
 3   label     17769 non-null  str
dtypes: int64(1), str(3)
memory usage: 555.4 KB

In [5]:
train["label"].value_counts()

label
technical_support    10642
other                 3800
customer_support      3327
Name: count, dtype: int64

In [6]:
train["label"].value_counts(normalize=True)

label
technical_support    0.598908
other                0.213856
customer_support     0.187236
Name: proportion, dtype: float64

In [7]:
train["tag"].value_counts().head(20)

tag
Other                 2433
Brakes                 327
Pedals                 233
Gears/transmission     215
Electrical system      200
Kickstand              196
Battery                183
Handlebar              162
Saddle                 149
Motor                  147
Chain                  147
Vandalism              145
Firmware               120
QR code                104
Rear wheel              93
Front wheel             88
Ignition                74
Lose/worn parts         63
Display                 54
Dirty                   37
Name: count, dtype: int64

In [8]:
pd.crosstab(train["tag"], train["label"])

label               customer_support  other  technical_support
tag
Battery                          115      1                 67
Brakes                            40      8                279
Chain                             52      4                 91
Control panel                      5      0                  6
Dirty                             16      1                 20
Display                           10      3                 41
Electrical system                 79      2                119
Firmware                          87      4                 29
Frame                             13      1                 22
Front wheel                       13      3                 72
Gears/transmission                30      6                179
Handlebar                         17      4                141
Ignition                          37      1                 36
Kickstand                        146      9                 41
Lights                             4      0                 31
Lose/worn parts                   15      0                 48
Motor                             39      5                103
Other                            811     61               1561
Pedals                            19      3                211
QR code                           76      2                 26
Rear wheel                        22      0                 71
Saddle                            12      5                132
Suspension                         1      0                  1
Throttle                           1      0                 10
Vandalism                         18      4                123

In [9]:
train["feedback"].sample(20, random_state=42)

1086     3cü sürüş modu işləmirdi və zəncir atırdı tez-...
12402                              siqnalı olsa əla olardı
15938                                         tökülürdjfjd
14779            панель с зарядкой и скоростью не работает
4936                                  Accelerator problemi
17417    biyabirchiliq ,elektro goturmushem elektrosu i...
4338     spidometri düzgün gostermir. Ozu özünden çaxır...
15735                 velonun on rolu doğru tənzimlənməyib
736                               Sürətlənməsi problem var
101      çox pis hər dəfə yazıram amma deyəsən baxmrsın...
7518                                       звенят железяки
7075                             Здравствуйте! Руль сломан
7316                                    ayaq əyləci yoxdur
10269                ehmed recebliye dayanacag elave edin.
16824                      supereeebsuperrrsupereeesuperee
12596                   Замков не было и я так и не поехал
4026              Dəniz mall’ın qarşısına parking açın pls
3269     у самоката сломана подножка , он не стоит а па...
1347     Pedal deyil təkcə Şatun dağılıb Bir dəfə də gö...
5760                                           super super
Name: feedback, dtype: str

In [10]:
from sklearn.model_selection import train_test_split

X = train["feedback"]

y = train["label"]

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)

X_valid_vec = vectorizer.transform(X_valid)

In [12]:
from sklearn.svm import LinearSVC

model = LinearSVC()

model.fit(X_train_vec, y_train)

LinearSVC()

In [13]:
pred = model.predict(X_valid_vec)

In [14]:
from sklearn.metrics import classification_report

print(classification_report(y_valid, pred))

                   precision    recall  f1-score   support

 customer_support       0.83      0.80      0.81       665
            other       0.83      0.82      0.83       760
technical_support       0.92      0.93      0.92      2129

         accuracy                           0.88      3554
        macro avg       0.86      0.85      0.85      3554
     weighted avg       0.88      0.88      0.88      3554

In [15]:
from sklearn.metrics import f1_score

print(
    "Macro F1:",
    f1_score(
        y_valid,
        pred,
        average="macro"
    )
)

Macro F1: 0.854415465338043

In [16]:
train["text"] = (
    train["feedback"].fillna("")
    + " [SEP] "
    + train["tag"].fillna("")
)

In [17]:
train["text"] = (
    train["feedback"].fillna("")
    + " [SEP] "
    + train["tag"].fillna("")
)

In [18]:
X = train["text"]